spring:
  application:
    name: route
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hello

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
#    show-sql: true


server:
  port: 8080


eureka:
  client:
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8999/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
#zuul:
#  routes:
#    user: /route-user/**
